const fs = require("fs");
const path = require("path");
const withEngine = require("./src/engine/plugins/enginePlugin");

// ── Engine 404 fallback guard ─────────────────────────────────────────────────
const appNotFound = path.join(__dirname, "app", "not-found.tsx");
if (!fs.existsSync(appNotFound)) {
	fs.writeFileSync(
		appNotFound,
		[
			"// Auto-generated by engine — replace this file to use your own 404.",
			'export { default } from "../src/engine/not-found";',
			"",
		].join("\n"),
	);
	console.log("[engine] app/not-found.tsx missing — regenerated engine fallback.");
}

// ── Turbopack Client Mock Guard ───────────────────────────────────────────────
const turbopackStub = path.join(__dirname, "app", "__turbopack_stub__.ts");
if (!fs.existsSync(turbopackStub)) {
	fs.writeFileSync(turbopackStub, "export default {};\n");
}

/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true,
	distDir: "dist",

	// Allow phones/tablets on the local LAN to use the Next dev client, HMR,
	// RSC requests, and client-side navigation without cross-origin dev blocking.
	// This only affects development; production origin policy is unchanged.
	allowedDevOrigins: ["192.168.31.144"],

	images: {
		formats: ["image/avif", "image/webp"],
		qualities: [58, 72, 75],
		minimumCacheTTL: 60 * 60 * 24 * 30,

		// These are intentional same-origin image endpoints. They use query
		// parameters for city/country/slot/width, so the pathname is constrained
		// here while search params are deliberately left unrestricted.
		localPatterns: [
			{ pathname: "/api/city-photo" },
			{ pathname: "/api/city-image" },
		],

		remotePatterns: [
			{ protocol: "https", hostname: "images.unsplash.com" },
			{ protocol: "https", hostname: "upload.wikimedia.org" },
			{ protocol: "https", hostname: "thumb.wikimedia.org" },
		],
	},

	async headers() {
		return [
			{
				source: "/city-media/:path*",
				headers: [
					{ key: "Cache-Control", value: "public, max-age=31536000, immutable" },
				],
			},
		];
	},

	// ── Turbopack Compiler Configuration (Next.js 16 Stable) ──────────────────
	turbopack: {
		resolveAlias: {
			fs: { browser: "./app/__turbopack_stub__.ts" },
			"fs/promises": { browser: "./app/__turbopack_stub__.ts" },
			path: { browser: "./app/__turbopack_stub__.ts" },
			os: { browser: "./app/__turbopack_stub__.ts" },
			crypto: { browser: "./app/__turbopack_stub__.ts" },
		},
	},

	webpack(config, { isServer }) {
		if (!isServer) {
			config.resolve.fallback = {
				...(config.resolve.fallback ?? {}),
				fs: false,
				"fs/promises": false,
				path: false,
				os: false,
				crypto: false,
			};
		}
		return config;
	},
};

module.exports = withEngine(nextConfig);
