const fs   = require("fs");
const path = require("path");

// ── Engine 404 fallback guard ─────────────────────────────────────────────────
//  app/not-found.tsx is committed as a re-export shim that points to the
//  engine's built-in 404 page.  If a consumer removes the file without
//  replacing it, Next.js would fall through to its own plain white 404.
//  This guard regenerates the shim at startup so the engine default is always
//  the floor, not Next.js's default.
const appNotFound = path.join(__dirname, "app", "not-found.tsx");
if (!fs.existsSync(appNotFound)) {
	fs.writeFileSync(
		appNotFound,
		[
			"// Auto-generated by engine — replace this file to use your own 404.",
			'export { default } from "../src/engine/not-found";',
			"",
		].join("\n"),
	);
	console.log("[engine] app/not-found.tsx missing — regenerated engine fallback.");
}

/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true,
	distDir: "dist",
};

module.exports = nextConfig;
