const fs   = require("fs");
const path = require("path");

// ── Engine 404 fallback guard ─────────────────────────────────────────────────
const appNotFound = path.join(__dirname, "app", "not-found.tsx");
if (!fs.existsSync(appNotFound)) {
	fs.writeFileSync(
		appNotFound,
		[
			"// Auto-generated by engine — replace this file to use your own 404.",
			'export { default } from "../src/engine/not-found";',
			"",
		].join("\n"),
	);
	console.log("[engine] app/not-found.tsx missing — regenerated engine fallback.");
}

/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true,
	distDir: "dist",

	// ── Image optimisation ────────────────────────────────────────────────────
	//  Next.js will automatically serve AVIF → WebP → original format based on
	//  the Accept header. No changes needed in EngineImage — this is transparent.
	images: {
		// Priority order: AVIF (smallest, best quality) → WebP → original
		formats: ["image/avif", "image/webp"],
		// Breakpoints for srcset generation — covers all common device widths
		deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
		// Sizes for layout-contained images (icons, thumbnails, avatars)
		imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
		// Cache optimised images for 30 days
		minimumCacheTTL: 60 * 60 * 24 * 30,
	},

	webpack(config, { isServer }) {
		if (!isServer) {
			// ── Node.js built-in stubs for the client bundle ───────────────────────
			//  createPage.tsx contains an async server component that dynamically
			//  imports "fs/promises" to resolve markdown filePaths at render time.
			//  That code path never runs on the client, but webpack still needs to
			//  know what to do with the import. Stubbing these to `false` makes
			//  webpack emit an empty module — no runtime error, no bundle bloat.
			config.resolve.fallback = {
				...(config.resolve.fallback ?? {}),
				fs:            false,
				"fs/promises": false,
				path:          false,
				os:            false,
				crypto:        false,
			};
		}
		return config;
	},
};

module.exports = nextConfig;
