// Generated by Next.js Engine NENC plugin. Do not edit.
import type { NENCClientManifest } from "nextjs-engine/network";

function deepFreeze<T>(value: T): T {
	if (value && typeof value === "object" && !Object.isFrozen(value)) {
		Object.freeze(value);
		for (const nested of Object.values(value as Record<string, unknown>)) deepFreeze(nested);
	}
	return value;
}

export const NENC_CLIENT_MANIFEST = deepFreeze({
	"version": 1,
	"endpoint": "/_static/command",
	"buildId": "phase-c-local",
	"headers": {
		"selector": "x-hJU8Q3Klz",
		"nonce": "x-hpV291CLG",
		"timestamp": "x-hZs1m_y_M",
		"signature": "x-ho-161i8u"
	},
	"commands": {
		"privateSearch": {
			"id": "csRVUsj7H",
			"args": {
				"query": "aRi-hc92D"
			}
		}
	}
}) as NENCClientManifest;
