"use strict";

// Compiles statically declared EngineCommand metadata into separate client and
// server modules, then generates exactly one Next.js App Router endpoint.

const fs = require("fs");
const path = require("path");
const { compileNENCManifest, discoverNENCCommands } = require("./nencCompiler");

const GENERATED_MARKER = "// Generated by Next.js Engine NENC plugin. Do not edit.";
const WATCH_STATE_KEY = Symbol.for("nextjs-engine.nenc-watch-state");

function resolveInside(projectRoot, target, label) {
	const root = path.resolve(projectRoot);
	const resolved = path.resolve(root, String(target || ""));
	const relative = path.relative(root, resolved);
	if (!relative || relative === "." || relative.startsWith("..") || path.isAbsolute(relative)) {
		throw new Error(`[engine:nenc] ${label} must stay inside the project root.`);
	}
	return resolved;
}

function containsPath(parent, target) {
	const relative = path.relative(parent, target);
	return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

function normalizeCommandFiles(projectRoot, commandFiles) {
	if (!Array.isArray(commandFiles) || commandFiles.length === 0) {
		throw new Error("[engine:nenc] commandFiles must contain at least one project-relative file.");
	}
	const files = [...new Set(commandFiles.map((file) => resolveInside(projectRoot, file, "commandFiles")))].sort();
	for (const file of files) {
		if (!fs.existsSync(file) || !fs.statSync(file).isFile()) {
			throw new Error(`[engine:nenc] Command file does not exist: ${path.relative(projectRoot, file)}`);
		}
		if (!/\.[cm]?[jt]sx?$/.test(file)) {
			throw new Error(`[engine:nenc] Command files must be JavaScript or TypeScript: ${path.relative(projectRoot, file)}`);
		}
	}
	return files;
}

function importPath(fromFile, targetFile) {
	let relative = path.relative(path.dirname(fromFile), targetFile).split(path.sep).join("/");
	relative = relative.replace(/\.(?:[cm]?[jt]sx?)$/, "");
	if (!relative.startsWith(".")) relative = `./${relative}`;
	return relative;
}

function renderManifestModule(exportName, typeName, packageEntry, manifest) {
	return [
		GENERATED_MARKER,
		`import type { ${typeName} } from "${packageEntry}";`,
		"",
		"function deepFreeze<T>(value: T): T {",
		"\tif (value && typeof value === \"object\" && !Object.isFrozen(value)) {",
		"\t\tObject.freeze(value);",
		"\t\tfor (const nested of Object.values(value as Record<string, unknown>)) deepFreeze(nested);",
		"\t}",
		"\treturn value;",
		"}",
		"",
		`export const ${exportName} = deepFreeze(${JSON.stringify(manifest, null, "\t")}) as ${typeName};`,
		"",
	].join("\n");
}

function swapDirectory(stagingDirectory, outputDirectory) {
	const backupDirectory = `${outputDirectory}.backup-${process.pid}-${Date.now().toString(36)}`;
	const hadOutput = fs.existsSync(outputDirectory);
	let backedUp = false;
	let installed = false;
	try {
		if (hadOutput) {
			fs.renameSync(outputDirectory, backupDirectory);
			backedUp = true;
		}
		fs.renameSync(stagingDirectory, outputDirectory);
		installed = true;
	} catch (error) {
		if (!installed && backedUp && !fs.existsSync(outputDirectory) && fs.existsSync(backupDirectory)) {
			fs.renameSync(backupDirectory, outputDirectory);
			backedUp = false;
		}
		throw error;
	} finally {
		if (fs.existsSync(stagingDirectory)) fs.rmSync(stagingDirectory, { recursive: true, force: true });
		if (installed && backedUp && fs.existsSync(backupDirectory)) {
			fs.rmSync(backupDirectory, { recursive: true, force: true });
		}
	}
}

function assertRouteWritable(routeFile) {
	if (!fs.existsSync(routeFile)) return;
	const existing = fs.readFileSync(routeFile, "utf8");
	if (!existing.startsWith(GENERATED_MARKER)) {
		throw new Error(`[engine:nenc] Refusing to overwrite the existing route: ${routeFile}`);
	}
}

function writeRoute(routeFile, serverManifestFile, handlerModule, commandFiles) {
	const routeSource = [
		GENERATED_MARKER,
		...commandFiles.map((file) => `import "${importPath(routeFile, file)}";`),
		`import createNENCHandler from "${importPath(routeFile, handlerModule)}";`,
		`import { NENC_SERVER_MANIFEST } from "${importPath(routeFile, serverManifestFile)}";`,
		"",
		"const handler = createNENCHandler(NENC_SERVER_MANIFEST);",
		"",
		"export { handler as POST, handler as OPTIONS };",
		"",
	].join("\n");
	fs.mkdirSync(path.dirname(routeFile), { recursive: true });
	const temporaryFile = `${routeFile}.tmp-${process.pid}-${Date.now().toString(36)}`;
	const backupFile = `${routeFile}.backup-${process.pid}-${Date.now().toString(36)}`;
	let backedUp = false;
	let installed = false;
	try {
		fs.writeFileSync(temporaryFile, routeSource, "utf8");
		if (fs.existsSync(routeFile)) {
			fs.renameSync(routeFile, backupFile);
			backedUp = true;
		}
		fs.renameSync(temporaryFile, routeFile);
		installed = true;
	} catch (error) {
		if (!installed && backedUp && !fs.existsSync(routeFile) && fs.existsSync(backupFile)) {
			fs.renameSync(backupFile, routeFile);
			backedUp = false;
		}
		throw error;
	} finally {
		if (fs.existsSync(temporaryFile)) fs.rmSync(temporaryFile, { force: true });
		if (installed && backedUp && fs.existsSync(backupFile)) fs.rmSync(backupFile, { force: true });
	}
}

function compileNENCProject(options) {
	const projectRoot = path.resolve(options.projectRoot || process.cwd());
	const commandFiles = normalizeCommandFiles(projectRoot, options.commandFiles);
	const outputDirectory = resolveInside(projectRoot, options.outputDir || ".nextjs-engine/nenc", "outputDir");
	const publicDirectory = path.resolve(projectRoot, "public");
	const publicRelative = path.relative(publicDirectory, outputDirectory);
	if (!publicRelative.startsWith("..") && !path.isAbsolute(publicRelative)) {
		throw new Error("[engine:nenc] outputDir cannot be inside public/ because it contains the server manifest.");
	}

	const generateRoute = options.generateRoute !== false;
	const appDirectory = resolveInside(projectRoot, options.appDir || "app", "appDir");
	const routeFile = path.join(appDirectory, "_static", "command", "route.ts");
	if (containsPath(outputDirectory, appDirectory) || commandFiles.some((file) => containsPath(outputDirectory, file))) {
		throw new Error("[engine:nenc] outputDir cannot contain application or command source files.");
	}
	let handlerModule = null;
	if (generateRoute) {
		if (!options.handlerModule) throw new Error("[engine:nenc] handlerModule is required when route generation is enabled.");
		handlerModule = resolveInside(projectRoot, options.handlerModule, "handlerModule");
		if (!fs.existsSync(handlerModule) || !fs.statSync(handlerModule).isFile()) {
			throw new Error(`[engine:nenc] Handler module does not exist: ${path.relative(projectRoot, handlerModule)}`);
		}
		if (containsPath(outputDirectory, handlerModule)) {
			throw new Error("[engine:nenc] outputDir cannot contain the handler module.");
		}
		if (handlerModule === routeFile || commandFiles.includes(routeFile)) {
			throw new Error("[engine:nenc] Generated route cannot also be a command or handler module.");
		}
		assertRouteWritable(routeFile);
	}

	const commands = commandFiles.flatMap((file) => discoverNENCCommands(
		fs.readFileSync(file, "utf8"),
		path.relative(projectRoot, file).split(path.sep).join("/"),
	));
	if (commands.length === 0) {
		throw new Error("[engine:nenc] No static EngineCommand declarations were found in commandFiles.");
	}
	const manifest = compileNENCManifest(commands, { seed: options.seed, buildId: options.buildId });
	const stagingDirectory = `${outputDirectory}.staging-${process.pid}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
	fs.rmSync(stagingDirectory, { recursive: true, force: true });
	fs.mkdirSync(stagingDirectory, { recursive: true });

	const packageName = String(options.packageName || "nextjs-engine");
	if (!/^(?:@[a-z0-9._-]+\/)?[a-z0-9._-]+$/i.test(packageName)) {
		throw new Error("[engine:nenc] packageName is invalid.");
	}
	const clientFile = path.join(stagingDirectory, "client.ts");
	const serverFile = path.join(stagingDirectory, "server.ts");
	try {
		fs.writeFileSync(
			clientFile,
			renderManifestModule("NENC_CLIENT_MANIFEST", "NENCClientManifest", `${packageName}/network`, manifest.client),
			"utf8",
		);
		fs.writeFileSync(
			serverFile,
			renderManifestModule("NENC_SERVER_MANIFEST", "NENCServerManifest", `${packageName}/server`, manifest.server),
			"utf8",
		);
		fs.writeFileSync(path.join(stagingDirectory, "manifest.json"), `${JSON.stringify(manifest, null, "\t")}\n`, "utf8");
		swapDirectory(stagingDirectory, outputDirectory);
	} catch (error) {
		fs.rmSync(stagingDirectory, { recursive: true, force: true });
		throw error;
	}

	const installedServerFile = path.join(outputDirectory, "server.ts");
	if (generateRoute) writeRoute(routeFile, installedServerFile, handlerModule, commandFiles);
	return Object.freeze({
		manifest,
		commands: Object.freeze(commands),
		clientFile: path.join(outputDirectory, "client.ts"),
		serverFile: installedServerFile,
		routeFile: generateRoute ? routeFile : null,
	});
}

function watchNENCSources(options, compile) {
	const watchOverride = process.env.NEXTJS_ENGINE_NENC_WATCH;
	const isNextDev = process.env.NODE_ENV === "development" && process.argv.includes("dev");
	if (watchOverride === "0" || (watchOverride !== "1" && !isNextDev)) return;
	const root = globalThis;
	if (!root[WATCH_STATE_KEY]) root[WATCH_STATE_KEY] = new Map();
	const state = root[WATCH_STATE_KEY];
	const files = normalizeCommandFiles(options.projectRoot, options.commandFiles);
	const watchKey = files.join("\n");
	if (state.has(watchKey)) return;

	let timer = null;
	const queueCompile = () => {
		if (timer) clearTimeout(timer);
		timer = setTimeout(() => {
			timer = null;
			try {
				compile();
			} catch (error) {
				console.error("[engine:nenc] Failed to recompile commands:", error);
			}
		}, 50);
	};
	const watchers = files.map((file) => {
		const watcher = fs.watch(file, queueCompile);
		watcher.on("error", (error) => console.warn(`[engine:nenc] Watcher failed for ${file}:`, error));
		watcher.unref?.();
		return watcher;
	});
	state.set(watchKey, watchers);
}

function withEngineNENC(nextConfig = {}, pluginOptions = {}) {
	const projectRoot = process.cwd();
	const options = { ...pluginOptions, projectRoot };
	const compile = () => compileNENCProject(options);
	compile();
	watchNENCSources(options, compile);
	return { ...nextConfig };
}

module.exports = withEngineNENC;
module.exports.withEngineNENC = withEngineNENC;
module.exports.compileNENCProject = compileNENCProject;
module.exports.GENERATED_MARKER = GENERATED_MARKER;
