// Generated by Next.js Engine NENC plugin. Do not edit.
import "../../../src/example/private-search/commands";
import createNENCHandler from "../../../src/example/private-search/nenc.server";
import { NENC_SERVER_MANIFEST } from "../../../.nextjs-engine/nenc/server";

const handler = createNENCHandler(NENC_SERVER_MANIFEST);

export { handler as POST, handler as OPTIONS };
