import type { ECBounds,ECCamera,ECGroup,ECMaterial,ECMesh,ECNode,ECScene,ECTransform,ECVector2,ECVector3 } from "./ECTypes";
let idCounter=0;const nextId=(p:string)=>`${p}-${(idCounter++).toString(36)}`;export const ecVec2=(x:number,y:number):ECVector2=>({x,y});export const ecVec3=(x:number,y:number,z=0):ECVector3=>({x,y,z});
export function ecTransform(o:Partial<ECTransform>={}):ECTransform{return{position:o.position??ecVec3(0,0,0),rotation:o.rotation??ecVec3(0,0,0),scale:o.scale??ecVec3(1,1,1)}}
export function ecMaterial(o:Partial<ECMaterial>={}):ECMaterial{return{fill:o.fill,stroke:o.stroke,strokeWidth:o.strokeWidth??1,opacity:o.opacity??1,shading:o.shading??"flat",rimColor:o.rimColor,rimIntensity:o.rimIntensity??.5}}
function bounds(v:Float32Array):ECBounds{if(!v.length)return{min:ecVec3(0,0,0),max:ecVec3(0,0,0)};let ax=Infinity,ay=Infinity,az=Infinity,bx=-Infinity,by=-Infinity,bz=-Infinity;for(let i=0;i<v.length;i+=3){ax=Math.min(ax,v[i]);ay=Math.min(ay,v[i+1]);az=Math.min(az,v[i+2]);bx=Math.max(bx,v[i]);by=Math.max(by,v[i+1]);bz=Math.max(bz,v[i+2])}return{min:ecVec3(ax,ay,az),max:ecVec3(bx,by,bz)}}
function mesh(topology:ECMesh["topology"],vertices:Float32Array,material:ECMaterial,transform:ECTransform,indices?:Uint16Array|Uint32Array):ECMesh{return{id:nextId("mesh"),type:"mesh",vertices,indices,material,transform,topology,vertexCount:()=>vertices.length/3,faceCount:()=>indices?indices.length/3:topology==="fan"?Math.max(0,vertices.length/3-2):0,bounds:()=>bounds(vertices),center:()=>{const b=bounds(vertices);return ecVec3((b.min.x+b.max.x)/2,(b.min.y+b.max.y)/2,(b.min.z+b.max.z)/2)}}}
export function ecCircle(radius:number,o:{segments?:number;material?:Partial<ECMaterial>;transform?:Partial<ECTransform>}={}):ECMesh{const s=o.segments??48,v=new Float32Array((s+2)*3);for(let i=0;i<=s;i++){const a=i/s*Math.PI*2,n=(i+1)*3;v[n]=Math.cos(a)*radius;v[n+1]=Math.sin(a)*radius}return mesh("fan",v,ecMaterial(o.material),ecTransform(o.transform))}
export function ecRect(width:number,height:number,o:{material?:Partial<ECMaterial>;transform?:Partial<ECTransform>}={}):ECMesh{const x=width/2,y=height/2;return mesh("fan",new Float32Array([-x,-y,0,x,-y,0,x,y,0,-x,y,0]),ecMaterial(o.material),ecTransform(o.transform))}
export function ecPath(source:string|ECVector2[],o:{material?:Partial<ECMaterial>;transform?:Partial<ECTransform>}={}):ECMesh{const p=typeof source==="string"?parsePathString(source):source,v=new Float32Array(p.length*3);p.forEach((q,i)=>{v[i*3]=q.x;v[i*3+1]=q.y});return mesh("strip",v,ecMaterial(o.material),ecTransform(o.transform))}
function parsePathString(d:string):ECVector2[]{const t=d.match(/[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?/g)??[],p:ECVector2[]=[];let i=0,c="",cur=ecVec2(0,0),start=ecVec2(0,0),lc:ECVector2|null=null,lq:ECVector2|null=null;const cmd=(v?:string)=>!!v&&/^[a-zA-Z]$/.test(v),has=()=>i<t.length&&!cmd(t[i]),num=()=>{const n=Number(t[i++]);return Number.isFinite(n)?n:0},add=(x:number,y:number)=>{if(Number.isFinite(x)&&Number.isFinite(y)){cur=ecVec2(x,y);p.push(cur)}},pt=(x:number,y:number,r:boolean)=>r?ecVec2(cur.x+x,cur.y+y):ecVec2(x,y),reflect=(q:ECVector2|null)=>q?ecVec2(2*cur.x-q.x,2*cur.y-q.y):cur;
const cubic=(a:ECVector2,b:ECVector2,e:ECVector2)=>{const s=cur;for(let n=1;n<=16;n++){const u=n/16,m=1-u;add(m*m*m*s.x+3*m*m*u*a.x+3*m*u*u*b.x+u*u*u*e.x,m*m*m*s.y+3*m*m*u*a.y+3*m*u*u*b.y+u*u*u*e.y)}};const quad=(q:ECVector2,e:ECVector2)=>{const s=cur;for(let n=1;n<=12;n++){const u=n/12,m=1-u;add(m*m*s.x+2*m*u*q.x+u*u*e.x,m*m*s.y+2*m*u*q.y+u*u*e.y)}};const angle=(ux:number,uy:number,vx:number,vy:number)=>{const l=Math.hypot(ux,uy)*Math.hypot(vx,vy);if(!l)return 0;const a=Math.acos(Math.max(-1,Math.min(1,(ux*vx+uy*vy)/l)));return ux*vy-uy*vx<0?-a:a};const arc=(rx0:number,ry0:number,rot:number,large:boolean,sweep:boolean,e:ECVector2)=>{let rx=Math.abs(rx0),ry=Math.abs(ry0);const s=cur;if(!rx||!ry||(s.x===e.x&&s.y===e.y)){add(e.x,e.y);return}const ph=rot%360*Math.PI/180,cp=Math.cos(ph),sp=Math.sin(ph),dx=(s.x-e.x)/2,dy=(s.y-e.y)/2,xp=cp*dx+sp*dy,yp=-sp*dx+cp*dy,k=xp*xp/(rx*rx)+yp*yp/(ry*ry);if(k>1){const z=Math.sqrt(k);rx*=z;ry*=z}const nu=Math.max(0,rx*rx*ry*ry-rx*rx*yp*yp-ry*ry*xp*xp),de=rx*rx*yp*yp+ry*ry*xp*xp,co=(large===sweep?-1:1)*(de?Math.sqrt(nu/de):0),cxp=co*rx*yp/ry,cyp=co*-ry*xp/rx,cx=cp*cxp-sp*cyp+(s.x+e.x)/2,cy=sp*cxp+cp*cyp+(s.y+e.y)/2,ux=(xp-cxp)/rx,uy=(yp-cyp)/ry,vx=(-xp-cxp)/rx,vy=(-yp-cyp)/ry;let a=angle(1,0,ux,uy),da=angle(ux,uy,vx,vy);if(!sweep&&da>0)da-=Math.PI*2;if(sweep&&da<0)da+=Math.PI*2;const steps=Math.max(8,Math.ceil(Math.abs(da)/(Math.PI/12)));for(let n=1;n<=steps;n++){const q=a+da*n/steps;add(cx+cp*rx*Math.cos(q)-sp*ry*Math.sin(q),cy+sp*rx*Math.cos(q)+cp*ry*Math.sin(q))}};
while(i<t.length){if(cmd(t[i]))c=t[i++];if(!c){i++;continue}const r=c===c.toLowerCase(),u=c.toUpperCase();if(u!=="C"&&u!=="S")lc=null;if(u!=="Q"&&u!=="T")lq=null;switch(u){case"M":{if(!has())break;const q=pt(num(),num(),r);add(q.x,q.y);start=q;c=r?"l":"L";break}case"L":{if(!has())break;const q=pt(num(),num(),r);add(q.x,q.y);break}case"H":{if(!has())break;const x=num();add(r?cur.x+x:x,cur.y);break}case"V":{if(!has())break;const y=num();add(cur.x,r?cur.y+y:y);break}case"C":{if(!has())break;const a=pt(num(),num(),r),b=pt(num(),num(),r),e=pt(num(),num(),r);cubic(a,b,e);lc=b;break}case"S":{if(!has())break;const a=reflect(lc),b=pt(num(),num(),r),e=pt(num(),num(),r);cubic(a,b,e);lc=b;break}case"Q":{if(!has())break;const q=pt(num(),num(),r),e=pt(num(),num(),r);quad(q,e);lq=q;break}case"T":{if(!has())break;const q=reflect(lq),e=pt(num(),num(),r);quad(q,e);lq=q;break}case"A":{if(!has())break;const rx=num(),ry=num(),rot=num(),large=num()!==0,sweep=num()!==0,e=pt(num(),num(),r);arc(rx,ry,rot,large,sweep,e);break}case"Z":if(cur.x!==start.x||cur.y!==start.y)add(start.x,start.y);c="";break;default:c=""}}return p}
export const ecLine=(points:ECVector2[],o:any={})=>ecPath(points,o);export function ecPolygon(points:ECVector2[],o:any={}):ECMesh{const v=new Float32Array(points.length*3);points.forEach((p,i)=>{v[i*3]=p.x;v[i*3+1]=p.y});return mesh("fan",v,ecMaterial(o.material),ecTransform(o.transform))}export const ecGroup=(children:ECNode[],transform:Partial<ECTransform>={}):ECGroup=>({id:nextId("group"),type:"group",children,transform:ecTransform(transform)});export const ecScene=(children:ECNode[],o:{camera?:ECCamera;environment?:ECScene["environment"];background?:string}={}):ECScene=>({id:nextId("scene"),type:"scene",children,camera:o.camera,environment:o.environment??"void",background:o.background});export const ecVoidEnvironment:ECScene["environment"]="void";
