"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const { captureEngineSEOWebsitePreview } = require("./engineSEOCapture");

const GENERATED_MARKER = "// @generated by nextjs-engine EngineSEO — do not edit.";
const PAGE_FILE = /^page\.(?:js|jsx|ts|tsx)$/;
const PAGES_FILE = /\.(?:js|jsx|ts|tsx)$/;
const INTERCEPTING_ROUTE_SEGMENT = /^\(\.{1,3}\)/;

function normalizeImportPath(value) {
	const withoutExtension = value.replace(/\.(?:js|jsx|ts|tsx)$/, "");
	const normalized = withoutExtension.split(path.sep).join("/");
	return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

function walk(directory, visitor) {
	if (!fs.existsSync(directory)) return;
	for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
		const absolute = path.join(directory, entry.name);
		if (entry.isDirectory()) {
			if (["node_modules", ".next", "dist"].includes(entry.name)) continue;
			walk(absolute, visitor);
		} else if (entry.isFile()) visitor(absolute, entry.name);
	}
}

function isNonCanonicalAppSegment(segment) {
	return segment.startsWith("_")
		|| segment.startsWith("@")
		|| INTERCEPTING_ROUTE_SEGMENT.test(segment);
}

function routeFromAppPage(appDirectory, filename) {
	const directory = path.dirname(path.relative(appDirectory, filename));
	if (directory === ".") return "/";
	const segments = directory.split(path.sep);
	if (segments.some(isNonCanonicalAppSegment)) return null;
	const route = segments.filter((segment) => !(segment.startsWith("(") && segment.endsWith(")")));
	if (route.some((segment) => segment.includes("["))) return null;
	return route.length ? `/${route.join("/")}` : "/";
}

function routeFromPagesPage(pagesDirectory, filename) {
	const relative = path.relative(pagesDirectory, filename).split(path.sep).join("/");
	if (relative.startsWith("api/") || relative.startsWith("_") || relative.includes("[")) return null;
	const withoutExtension = relative.replace(PAGES_FILE, "");
	if (withoutExtension === "index") return "/";
	return `/${withoutExtension.endsWith("/index") ? withoutExtension.slice(0, -6) : withoutExtension}`.replace(/\/{2,}/g, "/");
}

function discoverEngineSEORouteSources(rootDirectory, configuredRoutes = []) {
	const routes = new Map(configuredRoutes
		.filter((route) => typeof route === "string" && route.startsWith("/"))
		.map((route) => [route, undefined]));
	const addRoute = (route, filename) => {
		if (!route) return;
		if (!routes.has(route) || !routes.get(route)) routes.set(route, filename);
	};
	for (const appDirectory of [path.join(rootDirectory, "app"), path.join(rootDirectory, "src", "app")]) {
		walk(appDirectory, (filename, basename) => {
			if (!PAGE_FILE.test(basename)) return;
			addRoute(routeFromAppPage(appDirectory, filename), filename);
		});
	}
	for (const pagesDirectory of [path.join(rootDirectory, "pages"), path.join(rootDirectory, "src", "pages")]) {
		walk(pagesDirectory, (filename, basename) => {
			if (!PAGES_FILE.test(basename)) return;
			addRoute(routeFromPagesPage(pagesDirectory, filename), filename);
		});
	}
	return new Map([...routes].sort(([left], [right]) => left === "/" ? -1 : right === "/" ? 1 : left.localeCompare(right)));
}

function discoverEngineSEORoutes(rootDirectory, configuredRoutes = []) {
	return [...discoverEngineSEORouteSources(rootDirectory, configuredRoutes).keys()];
}

function isoTimestamp(value, label) {
	const date = value instanceof Date ? value : new Date(value);
	if (Number.isNaN(date.getTime())) throw new Error(`[EngineSEO] ${label} must be a valid date.`);
	return date.toISOString();
}

function gitLastModified(rootDirectory, filename) {
	if (!filename) return undefined;
	const relative = path.relative(rootDirectory, filename);
	if (!relative || relative.startsWith("..") || path.isAbsolute(relative)) return undefined;
	const gitPath = relative.split(path.sep).join("/");
	const result = spawnSync("git", ["-C", rootDirectory, "log", "-1", "--format=%cI", "--", gitPath], {
		encoding: "utf8",
		windowsHide: true,
	});
	if (result.error || result.status !== 0) return undefined;
	const value = result.stdout.trim();
	if (!value || Number.isNaN(new Date(value).getTime())) return undefined;
	return new Date(value).toISOString();
}

function addAutomaticLastModified(route, source, mode, rootDirectory, buildTime) {
	if (route.lastModified !== undefined || mode === false) return route;
	const lastModified = mode === "build" ? buildTime : gitLastModified(rootDirectory, source);
	return lastModified ? { ...route, lastModified } : route;
}

function assertJsonSchema(value) {
	let encoded;
	try {
		encoded = JSON.stringify(value);
	} catch (error) {
		throw new Error(`[EngineSEO] SEO schema must be JSON-serializable: ${error instanceof Error ? error.message : String(error)}`);
	}
	if (encoded === undefined) throw new Error("[EngineSEO] SEO schema must be a JSON object.");
	return encoded;
}

function generatedFunctionSource(routeDirectory, modulePath, schema, method) {
	const importPath = normalizeImportPath(path.relative(routeDirectory, modulePath));
	return [
		GENERATED_MARKER,
		`import { createEngineSEO } from ${JSON.stringify(importPath)};`,
		"",
		`const engineseo = createEngineSEO(${assertJsonSchema(schema)});`,
		`export default engineseo.${method};`,
		"",
	].join("\n");
}

function generatedImageSource(routeDirectory, modulePath, schema) {
	const importPath = normalizeImportPath(path.relative(routeDirectory, modulePath));
	const preview = schema.preview?.mode === "generated" ? schema.preview : {};
	const width = Number(preview.width) || 1200;
	const height = Number(preview.height) || 630;
	const alt = schema.page?.title || schema.site?.defaultTitle || schema.site?.name || "Website preview";
	return [
		GENERATED_MARKER,
		`import { createEngineSEOImageResponse } from ${JSON.stringify(importPath)};`,
		"",
		`const schema = ${assertJsonSchema(schema)};`,
		`export const alt = ${JSON.stringify(alt)};`,
		`export const size = { width: ${width}, height: ${height} };`,
		'export const contentType = "image/png";',
		"export default function EngineSEOOpenGraphImage() {",
		"\treturn createEngineSEOImageResponse(schema, size);",
		"}",
		"",
	].join("\n");
}

function writeGeneratedFile(filename, source) {
	if (fs.existsSync(filename)) {
		const existing = fs.readFileSync(filename, "utf8");
		if (!existing.startsWith(GENERATED_MARKER)) return { filename, generated: false, reason: "application-owned" };
		if (existing === source) return { filename, generated: true, changed: false };
	}
	fs.mkdirSync(path.dirname(filename), { recursive: true });
	fs.writeFileSync(filename, source, "utf8");
	return { filename, generated: true, changed: true };
}

function removeGeneratedFile(filename) {
	if (!fs.existsSync(filename)) return;
	const existing = fs.readFileSync(filename, "utf8");
	if (existing.startsWith(GENERATED_MARKER)) fs.unlinkSync(filename);
}

function prepareEngineSEORoutes(options = {}) {
	const rootDirectory = path.resolve(options.rootDir || process.cwd());
	const appDirectory = fs.existsSync(path.join(rootDirectory, "src", "app")) && !fs.existsSync(path.join(rootDirectory, "app"))
		? path.join(rootDirectory, "src", "app")
		: path.join(rootDirectory, "app");
	const files = {
		sitemap: path.join(appDirectory, "sitemap.ts"),
		robots: path.join(appDirectory, "robots.ts"),
		openGraphImage: path.join(appDirectory, "opengraph-image.tsx"),
	};
	if (!options.schema || options.enabled === false) {
		Object.values(files).forEach(removeGeneratedFile);
		return { routes: [], files };
	}
	const schema = JSON.parse(assertJsonSchema(options.schema));
	const automatic = options.generate || {};
	if (automatic.sitemap !== false && !schema.site?.url) {
		throw new Error("[EngineSEO] seo.schema.site.url is required for automatic sitemap generation.");
	}
	const configuredRoutes = Array.isArray(schema.sitemap?.routes) ? schema.sitemap.routes.map((route) => route.path) : [];
	const sources = discoverEngineSEORouteSources(rootDirectory, [...configuredRoutes, ...(options.pages || [])]);
	const routes = [...sources.keys()];
	const lastModifiedMode = schema.sitemap?.lastModified ?? "git";
	if (!["git", "build", false].includes(lastModifiedMode)) {
		throw new Error('[EngineSEO] sitemap.lastModified must be "git", "build", or false.');
	}
	const buildTime = lastModifiedMode === "build"
		? isoTimestamp(options.buildTime ?? new Date(), "seo.buildTime")
		: undefined;
	const withLastModified = (route) => addAutomaticLastModified(
		route,
		sources.get(route.path),
		lastModifiedMode,
		rootDirectory,
		buildTime,
	);
	if (Array.isArray(schema.sitemap?.routes)) {
		schema.sitemap = { ...schema.sitemap, routes: schema.sitemap.routes.map(withLastModified) };
	} else {
		schema.sitemap = { ...(schema.sitemap || {}), routes: routes.map((route) => withLastModified({ path: route })) };
	}
	const modulePath = path.resolve(options.modulePath || path.join(__dirname, "..", "core", "engineseo", "index.ts"));
	const imageModulePath = path.resolve(options.imageModulePath || path.join(__dirname, "..", "seo.ts"));
	const results = {};
	if (automatic.sitemap !== false) results.sitemap = writeGeneratedFile(files.sitemap, generatedFunctionSource(appDirectory, modulePath, schema, "sitemap"));
	else removeGeneratedFile(files.sitemap);
	if (automatic.robots !== false) results.robots = writeGeneratedFile(files.robots, generatedFunctionSource(appDirectory, modulePath, schema, "robots"));
	else removeGeneratedFile(files.robots);
	if (automatic.openGraphImage === true || schema.preview?.mode === "generated") results.openGraphImage = writeGeneratedFile(files.openGraphImage, generatedImageSource(appDirectory, imageModulePath, schema));
	else removeGeneratedFile(files.openGraphImage);
	return { routes, files, results };
}

function withEngineSEO(nextConfig = {}, options) {
	prepareEngineSEORoutes(options || {});
	return nextConfig;
}

module.exports = withEngineSEO;
module.exports.withEngineSEO = withEngineSEO;
module.exports.prepareEngineSEORoutes = prepareEngineSEORoutes;
module.exports.discoverEngineSEORouteSources = discoverEngineSEORouteSources;
module.exports.discoverEngineSEORoutes = discoverEngineSEORoutes;
module.exports.gitLastModified = gitLastModified;
module.exports.captureEngineSEOWebsitePreview = captureEngineSEOWebsitePreview;
module.exports.GENERATED_MARKER = GENERATED_MARKER;
