"use strict";

const fs = require("fs");
const path = require("path");

const GENERATED_MARKER = "// @generated by nextjs-engine EngineDebug — do not edit.";
const DEBUG_ROUTE_PARTS = ["%5Fengine", "debug"];
const PAGE_FILE = /^page\.(?:js|jsx|ts|tsx)$/;
const PAGES_FILE = /\.(?:js|jsx|ts|tsx)$/;

function normalizeImportPath(value) {
	const withoutExtension = value.replace(/\.(?:js|jsx|ts|tsx)$/, "");
	const normalized = withoutExtension.split(path.sep).join("/");
	return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

function decodeSegment(segment) {
	try {
		return decodeURIComponent(segment);
	} catch {
		return segment;
	}
}

function isRoutableSegment(segment) {
	if (segment.startsWith("(") && segment.endsWith(")")) return false;
	if (segment.startsWith("@")) return false;
	if (segment.startsWith("_") && !segment.toLowerCase().startsWith("%5f")) return false;
	if (segment.includes("(.)") || segment.includes("(..)")) return false;
	return true;
}

function appRoute(appDirectory, filename) {
	const directory = path.dirname(path.relative(appDirectory, filename));
	if (directory === ".") return "/";
	const segments = directory.split(path.sep);
	if (segments.some((segment) => segment.toLowerCase() === "%5fengine")) return null;
	if (segments.some((segment) => segment.startsWith("_") || segment.includes("(.)") || segment.includes("(..)"))) return null;
	const routable = segments.filter(isRoutableSegment).map(decodeSegment);
	return routable.length > 0 ? `/${routable.join("/")}` : "/";
}

function pagesRoute(pagesDirectory, filename) {
	const relative = path.relative(pagesDirectory, filename).split(path.sep).join("/");
	if (relative.startsWith("api/") || relative.startsWith("_")) return null;
	const withoutExtension = relative.replace(PAGES_FILE, "");
	const route = withoutExtension === "index"
		? "/"
		: withoutExtension.endsWith("/index")
			? `/${withoutExtension.slice(0, -6)}`
			: `/${withoutExtension}`;
	return route.replace(/\/{2,}/g, "/");
}

function walk(directory, visitor) {
	if (!fs.existsSync(directory)) return;
	for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
		const absolute = path.join(directory, entry.name);
		if (entry.isDirectory()) {
			if (entry.name === "node_modules" || entry.name === ".next" || entry.name === "dist") continue;
			walk(absolute, visitor);
			continue;
		}
		if (entry.isFile()) visitor(absolute, entry.name);
	}
}

function discoverEngineDebugPages(rootDirectory, configuredPages = []) {
	const routes = new Set(configuredPages.filter((entry) => typeof entry === "string" && entry.startsWith("/")));
	for (const appDirectory of [path.join(rootDirectory, "app"), path.join(rootDirectory, "src", "app")]) {
		walk(appDirectory, (filename, basename) => {
			if (!PAGE_FILE.test(basename)) return;
			const route = appRoute(appDirectory, filename);
			if (route) routes.add(route);
		});
	}
	for (const pagesDirectory of [path.join(rootDirectory, "pages"), path.join(rootDirectory, "src", "pages")]) {
		walk(pagesDirectory, (filename, basename) => {
			if (!PAGES_FILE.test(basename)) return;
			const route = pagesRoute(pagesDirectory, filename);
			if (route) routes.add(route);
		});
	}
	return [...routes].sort((left, right) => left === "/" ? -1 : right === "/" ? 1 : left.localeCompare(right));
}

function generatedRouteSource(routeDirectory, modulePath, pages) {
	const importPath = normalizeImportPath(path.relative(routeDirectory, modulePath));
	return [
		GENERATED_MARKER,
		`import { EngineDebugPage } from ${JSON.stringify(importPath)};`,
		"",
		`const pages = ${JSON.stringify(pages, null, "\t")} as const;`,
		"",
		"export default function EngineDebugRoute() {",
		"\treturn <EngineDebugPage pages={pages} />;",
		"}",
		"",
	].join("\n");
}

function removeGeneratedRoute(routeFile, rootDirectory) {
	if (!fs.existsSync(routeFile)) return;
	const existing = fs.readFileSync(routeFile, "utf8");
	if (!existing.startsWith(GENERATED_MARKER)) {
		throw new Error(`[EngineDebug] Refusing to remove non-generated route at ${routeFile}.`);
	}
	fs.unlinkSync(routeFile);
	let current = path.dirname(routeFile);
	const stop = path.resolve(rootDirectory);
	while (current.startsWith(stop) && current !== stop) {
		if (fs.readdirSync(current).length > 0) break;
		fs.rmdirSync(current);
		current = path.dirname(current);
	}
}

function removeDevelopmentTypeCache(rootDirectory, distDirectory = ".next") {
	const root = path.resolve(rootDirectory);
	const outputRoot = path.resolve(root, distDirectory);
	if (outputRoot === root || !outputRoot.startsWith(`${root}${path.sep}`)) {
		throw new Error(`[EngineDebug] Refusing to clean an unsafe Next.js distDir: ${distDirectory}.`);
	}
	const developmentTypes = path.join(outputRoot, "dev", "types");
	fs.rmSync(developmentTypes, { recursive: true, force: true });
}

function prepareEngineDebugRoute(options = {}) {
	const rootDirectory = path.resolve(options.rootDir || process.cwd());
	const appDirectory = fs.existsSync(path.join(rootDirectory, "src", "app")) && !fs.existsSync(path.join(rootDirectory, "app"))
		? path.join(rootDirectory, "src", "app")
		: path.join(rootDirectory, "app");
	const routeDirectory = path.join(appDirectory, ...DEBUG_ROUTE_PARTS);
	const routeFile = path.join(routeDirectory, "page.tsx");
	const development = process.env.NODE_ENV === "development";

	if (!development || options.enabled === false) {
		removeGeneratedRoute(routeFile, rootDirectory);
		removeDevelopmentTypeCache(rootDirectory, options.distDir);
		return { development: false, pages: [], routeFile };
	}

	const modulePath = path.resolve(options.modulePath || path.join(__dirname, "..", "debug", "EngineDebugPage.tsx"));
	if (!fs.existsSync(modulePath)) {
		throw new Error(`[EngineDebug] Debug page module is missing: ${modulePath}`);
	}
	const pages = discoverEngineDebugPages(rootDirectory, options.pages || []);
	const source = generatedRouteSource(routeDirectory, modulePath, pages);
	if (fs.existsSync(routeFile)) {
		const existing = fs.readFileSync(routeFile, "utf8");
		if (!existing.startsWith(GENERATED_MARKER)) {
			throw new Error(`[EngineDebug] The reserved /_engine/debug route is owned by ${routeFile}.`);
		}
		if (existing === source) return { development: true, pages, routeFile };
	}
	fs.mkdirSync(routeDirectory, { recursive: true });
	fs.writeFileSync(routeFile, source, "utf8");
	return { development: true, pages, routeFile };
}

function withEngineDebug(nextConfig = {}, options = {}) {
	prepareEngineDebugRoute({
		...options,
		distDir: options.distDir || nextConfig.distDir,
	});
	return nextConfig;
}

module.exports = withEngineDebug;
module.exports.withEngineDebug = withEngineDebug;
module.exports.prepareEngineDebugRoute = prepareEngineDebugRoute;
module.exports.discoverEngineDebugPages = discoverEngineDebugPages;
module.exports.GENERATED_MARKER = GENERATED_MARKER;
