// ─────────────────────────────────────────────────────────────────────────────
//  Engine — StyleCollector  (three-tier CSS classification)
//
//  Every CSS block generated by usePropStyles passes through here.
//  Blocks are sorted into three tiers based on how many page renders
//  have needed them, and output in cascade-safe order: Global → Group → Local.
//
//  ┌─────────────────────────────────────────────────────────────────────────┐
//  │  GLOBAL  — used on ALL pages, or explicitly forced global               │
//  │            (engine baseline, theme vars, layout / header CSS)           │
//  │            threshold: 10+ renders OR explicit addGlobal() call          │
//  │                                                                         │
//  │  GROUP   — same CSS block used across several pages (3–9 renders).     │
//  │            Shared variables, repeated component configs.                │
//  │            NOT a subset of Global — each tier is mutually exclusive.    │
//  │                                                                         │
//  │  LOCAL   — unique to one page (1–2 renders). Page-specific overrides,  │
//  │            one-off responsive values.                                   │
//  └─────────────────────────────────────────────────────────────────────────┘
//
//  Cross-render tracking lives in a module-level static Map so it accumulates
//  across all pages rendered by the same Node.js process (dev server + SSG).
//  After a full SSG build, frequently-used CSS has naturally promoted to
//  Group or Global tiers.
//
//  BUG-001 FIX — Hydration Mismatch:
//  collect() now emits CSS in insertion order with NO tier comments.
//  Tier classification is preserved for EngineGlobalStyles only.
//  Since server and client render the same component tree in the same order,
//  the insertion order is always identical, eliminating the mismatch.
//
//  EngineGlobalStyles component: put this in app/layout.tsx to pre-inject the
//  Global tier CSS into the <head> before any page-specific styles load.
// ─────────────────────────────────────────────────────────────────────────────

import React from "react";

// ── Tier thresholds ───────────────────────────────────────────────────────────

const TIER_GROUP  = 3;   // 3–9 page renders → GROUP
const TIER_GLOBAL = 10;  // 10+ page renders → GLOBAL

// ── Cross-render registry (module-level — persists across SSG page builds) ───

interface XEntry {
	css:   string;
	count: number;
	tier:  "global" | "group" | "local";
}

/** Module-level registry: survives across page renders in the same process. */
const _xReg = new Map<string, XEntry>();

/** Hashes explicitly forced global (addGlobal calls) — tier locked to global. */
const _forcedGlobal = new Set<string>();

// ── Short hash ────────────────────────────────────────────────────────────────

function _hash(s: string): string {
	let h = 0;
	for (let i = 0; i < s.length; i++) h = (Math.imul(31, h) + s.charCodeAt(i)) | 0;
	return Math.abs(h).toString(36).slice(0, 7);
}

function _tierOf(count: number, forced: boolean): "global" | "group" | "local" {
	if (forced || count >= TIER_GLOBAL) return "global";
	if (count >= TIER_GROUP)            return "group";
	return "local";
}

// ── StyleCollector class ──────────────────────────────────────────────────────

export class StyleCollector {
	// Per-render buckets — cleared between page renders
	private _global = new Map<string, string>();
	private _group  = new Map<string, string>();
	private _local  = new Map<string, string>();

	// ── BUG-001 FIX: insertion-order tracking ────────────────────────────────
	// _orderedKeys records keys in the order they were first added this render.
	// collect() emits CSS in this order instead of tier-bucket order,
	// ensuring server and client produce identical strings every time.
	private _orderedKeys: string[] = [];
	private _seen        = new Set<string>();

	// ── Add a CSS block (auto-classified by cross-render frequency) ───────────

	add(cssBlock: string): void {
		if (!cssBlock) return;
		const key     = _hash(cssBlock);
		const forced  = _forcedGlobal.has(key);
		const entry   = _xReg.get(key);

		if (entry) {
			// Already seen in a prior render — bump count, maybe promote
			entry.count++;
			entry.tier = _tierOf(entry.count, forced);
		} else {
			// First time we've seen this block
			_xReg.set(key, { css: cssBlock, count: 1, tier: "local" });
		}

		const tier = _xReg.get(key)!.tier;
		this._putInBucket(key, cssBlock, tier);

		// Track insertion order — only record each key once per render
		if (!this._seen.has(key)) {
			this._seen.add(key);
			this._orderedKeys.push(key);
		}
	}

	/** Force a CSS block into the Global tier permanently (explicit global). */
	addGlobal(cssBlock: string): void {
		if (!cssBlock) return;
		const key = _hash(cssBlock);
		_forcedGlobal.add(key);
		_xReg.set(key, { css: cssBlock, count: TIER_GLOBAL, tier: "global" });
		this._putInBucket(key, cssBlock, "global");

		if (!this._seen.has(key)) {
			this._seen.add(key);
			this._orderedKeys.push(key);
		}
	}

	/** Register multiple blocks at once. */
	addMany(blocks: string[]): void {
		for (const b of blocks) this.add(b);
	}

	// ── Collect CSS in insertion order (BUG-001 FIX) ─────────────────────────

	/**
	 * Returns all CSS for this render in insertion order.
	 *
	 * IMPORTANT: No tier comments are emitted. Comments caused hydration
	 * mismatches when the server (long-running) promoted CSS to a higher
	 * tier than the fresh client. Tier data is preserved in _xReg for
	 * EngineGlobalStyles pre-injection, but does not affect CSS output.
	 */
	collect(): string {
		const parts: string[] = [];

		for (const key of this._orderedKeys) {
			// The block lives in exactly one tier bucket — find it
			const css =
				this._global.get(key) ??
				this._group.get(key)  ??
				this._local.get(key);
			if (css) parts.push(css);
		}

		return parts.join("\n");
	}

	/** Clear per-render buckets and insertion-order tracking. */
	reset(): void {
		this._global.clear();
		this._group.clear();
		this._local.clear();
		this._orderedKeys = [];
		this._seen.clear();
	}

	get size(): number {
		return this._seen.size;
	}

	// ── Internal ──────────────────────────────────────────────────────────────

	private _putInBucket(key: string, css: string, tier: "global" | "group" | "local"): void {
		// A block can only live in ONE tier — remove from lower tiers if promoted
		if (tier === "global") {
			this._global.set(key, css);
			this._group.delete(key);
			this._local.delete(key);
		} else if (tier === "group") {
			if (!this._global.has(key)) {
				this._group.set(key, css);
				this._local.delete(key);
			}
		} else {
			if (!this._global.has(key) && !this._group.has(key)) {
				this._local.set(key, css);
			}
		}
	}

	// ── Static helpers for layout injection ───────────────────────────────────

	/**
	 * Returns all CSS currently in the Global tier of the cross-render registry.
	 * Use inside EngineGlobalStyles (layout.tsx) to pre-inject shared CSS.
	 * On cold start this may be empty — it fills up over SSG builds or
	 * dev navigation.
	 */
	static getRegistryGlobalCSS(): string {
		const blocks: string[] = [];
		for (const [, entry] of _xReg) {
			if (entry.tier === "global") blocks.push(entry.css);
		}
		return blocks.join("\n");
	}

	/**
	 * Reset the cross-render registry.
	 * Called per-request in development to prevent cross-request tier
	 * accumulation from causing hydration mismatches.
	 * In production/SSG, this is never called — the registry accumulates
	 * naturally across page builds.
	 */
	static _resetRegistry(): void {
		_xReg.clear();
		_forcedGlobal.clear();
	}
}

// ── Singleton ─────────────────────────────────────────────────────────────────

/**
 * Module-level collector shared by all engine components in a render pass.
 * Next.js serialises SSR renders, so sharing this is safe on the server.
 * On the client it is never written to — styles are already in the DOM.
 */
export const globalStyleCollector = new StyleCollector();

// ── EngineGlobalStyles component ──────────────────────────────────────────────

/**
 * Renders a <style> tag containing the engine's Global-tier CSS.
 *
 * Place inside the <head> in app/layout.tsx so Global CSS loads on every page
 * before any page-specific styles:
 *
 * ```tsx
 * // app/layout.tsx
 * import { EngineGlobalStyles } from "@/engine";
 *
 * export default function Layout({ children }) {
 *   return (
 *     <html>
 *       <head>
 *         <EngineGlobalStyles />
 *       </head>
 *       <body>{children}</body>
 *     </html>
 *   );
 * }
 * ```
 *
 * Works best after a warm SSG build or several dev-server navigations —
 * that is when the Global tier has enough data to be meaningful.
 * On a cold start it renders an empty (but harmless) <style> tag.
 */
export function EngineGlobalStyles(): React.ReactElement | null {
	const css = StyleCollector.getRegistryGlobalCSS();
	if (!css) return null;
	return React.createElement("style", {
		id: "eng-global",
		// biome-ignore lint/security/noDangerouslySetInnerHtml: engine-generated CSS
		dangerouslySetInnerHTML: { __html: css },
	});
}
